title: Using Diet in ML
description: A demo on how to use dietary data in machine learning
theme: just-the-docs
markdown: kramdown

url: https://swi1.github.io/demo/

aux_links:
  GitHub Repository: https://github.com/SWi1/demo
